name: Python package CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: mydatabase
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U myuser -d mydatabase"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest psycopg2-binary
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Wait for PostgreSQL to be ready
      run: |
        for i in {1..30}; do
          pg_isready -h localhost -U myuser -d mydatabase && break
          echo "Waiting for database to be ready... ($i/30)"
          sleep 1
        done

    - name: Print environment variables
      run: printenv

    - name: Check PostgreSQL logs
      run: docker logs $(docker ps -q --filter "name=postgres")

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      env:
        POSTGRES_DB: mydatabase
        POSTGRES_USER: myuser
        POSTGRES_PASSWORD: mypassword
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
      run: |
        pytest
